package za.co.oldmutual.asisa.refdata;

public class RefDataDAOQueries {

	private RefDataDAOQueries() {

	}

	public static final String FETCH_CLAIM_TYPES_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_CLAIM_TYPE";

	public static final String FETCH_CLAIM_CATEGORY_QUERY = "SELECT ID as CODE, DESCRIPTION, CLAIM_TYPE FROM REF_CLAIM_CATEGORY";

	public static final String FETCH_CLAIM_STATUS_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_CLAIM_STATUS";

	public static final String FETCH_CLAIM_CAUSE_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_CLAIM_CAUSE";

	public static final String FETCH_IMPAIRMENT_CODES_QUERY = "SELECT ID as CODE, DESCRIPTION, GROUP_ID FROM REF_IMPAIRMENT_CODE";

	public static final String FETCH_PAYMENT_METHOD_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_PAYMENT_METHOD";

	public static final String FETCH_POLICY_TYPES_QUERY = "SELECT ID as CODE, DESCRIPTION, CLAIM_TYPE FROM REF_POLICY_TYPE";

	public static final String FETCH_LIFE_SPEC_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_LIFE_SPEC";

	public static final String FETCH_LIFE_SYMBOL_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_LIFE_SYMBOL";

	public static final String FETCH_IDENTITY_TYPES_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_IDTYPE";

	public static final String FETCH_TITLES_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_TITLE";

	public static final String FETCH_GENDERS_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_GENDER";

	public static final String FETCH_NOTIFICATION_TYPES_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_NOTIFICATION_TYPE";

	public static final String FETCH_NOTIFICATION_STATUS_QUERY = "SELECT ID as CODE, DESCRIPTION FROM REF_NOTIFICATION_STATUS";

	public static final String FETCH_OFFICE_QUERY_BY_LOCATION_ID_AND_OFFICE_ID = "SELECT ID FROM REF_OFFICE WHERE  LOCATION_ID = :locationID and  OFFICE_ID = :officeID";

	public static final String FETCH_OFFICE_QUERY_BY_ID = "SELECT ID, NAME,LOCATION_ID,OFFICE_ID, DESCRIPTION FROM REF_OFFICE";

	public static final String FETCH_READINGS_QUERY = "SELECT ID as CODE, IMPAIRMENT_CODE, FORMAT FROM REF_IMPAIRMENT_READINGS";
}
