package za.co.oldmutual.asisa.refdata;

public enum RefTypeEnum {
    EMPTY, TITLE, GENDER, IDTYPE, LIFE_SYMBOL, LIFE_SPEC, POLICY_TYPE, PAYMENT_METHOD, IMPAIRMENT_CODE, CLAIM_TYPE, CLAIM_CAUSE,
    CLAIM_STATUS, CLAIM_CATEGORY, CLAIM_REASON, NOTIFICATION_TYPE, NOTIFICATION_STATUS,OFFICE,READINGS;
}
