package za.co.oldmutual.asisa.common.bean;

public enum DataBaseColumnEnum {
  NOTIFICATION_ID,PERSON_ID,CLAIM_REASON_CODES,LIFE_SPEC_CODES,LIFE_SYMBOL_CODES,READINGS,TIME_SIGNAL,DESCRIPTION,EVENT_DEATH_PLACE,EVENT_DEATH_CERTIFICATE_NO,DHA1663_NUMBER,EVENT_CAUSE_CODE,CLAIM_STATUS_CODE,CLAIM_CATEGORY_CODE,EVENT_DATE
}
